---
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: virtualbox
lint:
  name: yamllint
platforms:
  - name: redis
    box: centos/7
    memory: 4096
provisioner:
  name: ansible
scenario:
  name: single-node
verifier:
  name: testinfra
  options:
    v: 1
  lint:
    name: flake8
