---
dependency:
  name: galaxy
driver:
  name: vagrant
lint:
  name: yamllint
  enabled: false
platforms:
  - name: redis
    box: centos/7
    memory: 4096
provisioner:
  name: ansible
  playbooks:
    setup: ../common/create.yml
    teardown: ../common/destroy.yml
    converge: playbook.yml
scenario:
  name: default
verifier:
  name: testinfra
  options:
    v: 1
  lint:
    name: flake8
