---

# The core package will install evrything required on a server to setup one
# or multiplle redis nodes.
#
# tasks file for redis
- name: Install redis packages
  package:
    name: "{{ item }}"
    state: present
  with_items:
    "{{ redis_packages }}"

# Required for selinux changes
# Add the ports to SELINUX context redis_t (port + cluster port)
- name: Install selinux policy support packages
  package:
    name: policycoreutils-python
  when: ansible_os_family == "RedHat"

- name: Create data dir
  file:
    path: "{{ redis_data_dir }}"
    state: directory
    owner: redis
    group: redis
    mode: 0755

- name: Create conf dir
  file:
    path: "{{ redis_conf_dir }}"
    state: directory
    owner: redis
    group: redis
    mode: 0755

- name: Create logs dir
  file:
    path: "{{ redis_log_dir }}"
    state: directory
    owner: redis
    group: redis
    mode: 0755

- name: Create run directory
  file:
    path: "{{ redis_run_dir }}"
    state: directory
    owner: redis
    group: redis
    mode: 0755

#Workaround the config dir to use is hardcoded in the script
- name: Fix conf dir in redis-shutdown
  replace:
    dest: /usr/libexec/redis-shutdown
    regexp: '^CONFIG_FILE=.*$'
    replace: 'CONFIG_FILE="{{ redis_conf_dir }}/$SERVICE_NAME.conf"'
