---
dependency:
  name: galaxy
driver:
  name: vagrant
lint:
  name: yamllint
  enabled: false
platforms:
  - name: redis-1
    groups:
    - redis-nodes
    - redis-mgt
    box: centos/7
    memory: 2048
    interfaces:
      - auto_config: true
        network_name: private_network
        type: dhcp
  - name: redis-2
    groups:
    - redis-nodes
    box: centos/7
    memory: 2048
    interfaces:
      - auto_config: true
        network_name: private_network
        type: dhcp
  - name: redis-3
    groups:
    - redis-nodes
    box: centos/7
    memory: 2048
    interfaces:
      - auto_config: true
        network_name: private_network
        type: dhcp
provisioner:
  name: ansible
scenario:
  name: stop-service
verifier:
  name: testinfra
  enabled: false
  options:
    v: 1
  lint:
    name: flake8
