---
- hosts: all
  become: true
  roles:
    - redis/core
    - redis/node

- hosts: redis_mgt
  become: true
  roles:
    - redis/cluster

- hosts: all
  become: true
  roles:
    - { role: redis/node, redis_state: stop }
